[package]
name = "uht-trace-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
oxigraph = "0.3"
sha2 = "0.10"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
